# Generated by Django 4.1.5 on 2023-02-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='userprofile/profile-picture.jpg', null=True, upload_to='userprofile'),
        ),
    ]
